name: Build

# TODO: limité à master, publier auto l'artifact sur pypi
# TODO: faire un script de validation des artifacts (recherche so)
on:
  push:
    branches:
      - master
    tags:
      - v[012].[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - 'README.md'
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.2.0a1

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        env:
          CIBW_SKIP: cp310-*
          # PIP_EXTRA_INDEX_URL: https://pypi.org/simple
          # PIP_INDEX_URL: https://test.pypi.org/simple


      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
