[tool.poetry]
name = "test-cythonpackage"
version = "0.0.0"
description = "Test cythonpackage"
authors = ["Philippe Prados <github@prados.fr>"]
license = "Apache-2.0"
packages = [
    { include = "foo" },
    { include = "foo2" },
    { include = "foo3" },
]
exclude = ["**/*.py"]
build = 'build.py'

[tool.poetry.dependencies]
python = "^3.7"
cython = "^0.29.24"
cythonpackage = "*"

[tool.poetry.dev-dependencies]
cibuildwheel = "2.1.3"
twine = "3.4.2"

[build-system]
requires = ["poetry>=1.0.0", "cython"]
build-backend = "poetry.masonry.api"

[[tool.poetry.source]]
# Accept local repository (see pypiserver)
name = "local"
url = "http://localhost:8888/simple"

# Use test.pypi.org
#name = "test-pypi"
#url = "https://test.pypi.org/simple"