[build-system]
requires = ["poetry>=1.2.0a2", "cythonpackage"]
build-backend = "poetry.masonry.api"

# Implicite setup.py d'après pep-0517
#build-backend = "setuptools.build_meta:X__legacy__ backend"



[tool.poetry]
name = "test-cythonpackage"
version = "0.0.0"
description = "Test cythonpackage"
authors = ["Philippe Prados <github@prados.fr>"]
license = "Apache-2.0"
packages = [
#    { include = "setup.*" },
    { include = "foo" },
#    { include = "foo2" },
#    { include = "foo3" },
]
#exclude = ["**/*.py"]
# Auto injecté dans le setup.py généré (bof), mais sinon n'invoque pas le setup.py build
# Voir wheel.py(108) Ouvrir un ticket ?
# Si pas de setup et pas de build, alors ne génère rien.
# C'est la cible en mode plugin
build = 'build.py'

[tool.poetry.plugins."poetry.plugin"]
cythonpackage = "cythonpackage.plugin:XXMyPlugin"

#[tool.poetry.plugins."poetry.application.plugin"]
#foo-command = "cythonpackage.plugin:MyApplicationPlugin"

[tool.poetry.dependencies]
python = "^3.7"
cython = "^0.29.24"
#cythonpackage = "0.0.0"
#cythonpackage = {path = "../"}

# [tool.poetry.dev-dependencies]
# cibuildwheel = "^2.1.*"
# twine = "^3.*"


# [build-system]
# requires = [
#     "setuptools>=42",
#     "wheel",
#     "Cython",
#     "cythonpackage"
# ]
# build-backend = "poetry.core.masonry.api"
#build-backend = "setuptools.build_meta"

# [[tool.poetry.source]]
# name = 'private'
# url = 'http://localhost:8888/simple'

# # Use test.pypi.org
# name = "test-pypi"
# url = "https://test.pypi.org/simple"