name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on:
  push:
    branches:
      - master
    tags:
      - v[012].[0-9]+.[0-9]+
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install pypa/build
        run: python -m pip install build wheel pbr twine --user

      - name: Build std bdist
        run: echo "CIBW_ENVIRONMENT=PBR_VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.2
        env:
          CIBW_BUILD: cp38-*

      - name: list
        run: ls ./wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_default:
    name: Build distribution without compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Install pypa/build
        run: python -m pip install build wheel pbr twine --user

      - name: Build std bdist
        run: PBR_VERSION="$(git describe --tags)" CYTHONPACKAGE=false python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'

      - name: Build sdist
        run: PBR_VERSION="$(git describe --tags)" python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [build_wheels, build_default, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TESTCYTHONPACKAGE_PYPI_API_TOKEN }}
